package jarista.project.spec;

import jarista.detail.DetailBuilder;
import jarista.detail.RoledDetail;
import jarista.spec.L3_Spec;

import java.util.List;

import static jarista.detail.DetailRole.*;

/** L3 — Java + Barista: the naming, coffee aesthetic, and visual identity. */
public class BaristaIdentity implements L3_Spec<CulturalStudies> {
    public static final BaristaIdentity INSTANCE = new BaristaIdentity();

    private static final DetailBuilder _db = new DetailBuilder();

    @Override
    public List<RoledDetail> details() {
        return List.of(
            _db.text()
                .ln("Jarista = Java + Barista.")
                .ln("A barista turns raw beans into something people actually want.")
                .ln("Jarista turns raw Java classes into a project structure")
                .ln("people can actually read and trust.")
            .as(DESCRIPTION),

            _db.text()
                .ln("The coffee palette — espresso background, crema nodes,")
                .ln("dark roast borders — is not decoration.")
                .ln("It is identity. The tool should feel like something")
                .ln("crafted with care, not generated by committee.")
            .as(DESIGN)
        );
    }
}
